#Tipo de identificacion
INSERT INTO TIPO_IDENTIFICACION (CODIGO,DESCRIPCION) VALUES ('CC','CEDULA DE CIUDADANIA');
INSERT INTO TIPO_IDENTIFICACION (CODIGO,DESCRIPCION) VALUES ('CE','CEDULA DE EXTRANJERIA');
INSERT INTO TIPO_IDENTIFICACION (CODIGO,DESCRIPCION) VALUES ('NIP','NUMERO DE IDENTIFICACION PERSONAL');
INSERT INTO TIPO_IDENTIFICACION (CODIGO,DESCRIPCION) VALUES ('NIT','NUMERO DE IDENTIFICACION TRIBUTARIA');
INSERT INTO TIPO_IDENTIFICACION (CODIGO,DESCRIPCION) VALUES ('TI','TARJETA DE IDENTIDAD');
INSERT INTO TIPO_IDENTIFICACION (CODIGO,DESCRIPCION) VALUES ('PAP','PASAPORTE');

SELECT * FROM tipo_identificacion;

#DueNos
INSERT INTO DUENOS (NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,DIRECCION,BARRIO,EMAIL,TELEFONO,ID_TIPO_IDENTIFICACION) VALUES ('1214746859','KEVIN','RESTREPO','CR 42 B # 110 BB - 24','POPULAR 1','KEVINRESCA@GMAIL.COM','3184913515',1);
INSERT INTO DUENOS (NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,DIRECCION,BARRIO,EMAIL,TELEFONO,ID_TIPO_IDENTIFICACION) VALUES ('43633782','NANCY','CARVAJAL','CR 42 B # 110 BB - 24','POPULAR 1','NANCYCARPANI@HOTMAIL.COM','5506407',1);
INSERT INTO DUENOS (NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,DIRECCION,BARRIO,EMAIL,TELEFONO,ID_TIPO_IDENTIFICACION) VALUES ('125488546','THOMAS','RESTREPO','CR 25 # 6 -26','COPACABANA','THOMASR@GMAIL.COM','333333',1);
INSERT INTO DUENOS (NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,DIRECCION,BARRIO,EMAIL,TELEFONO,ID_TIPO_IDENTIFICACION) VALUES ('987654321','JONATAN','PANIAGUA','CR 48 # 78 -110','ARANJUEZ','TATAN@YAHOO.ES','485520',1);
INSERT INTO DUENOS (NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,DIRECCION,BARRIO,EMAIL,TELEFONO,ID_TIPO_IDENTIFICACION) VALUES ('852147963','JULIANA','ZAPATA','CLL 25 # 11 - 26','ITAGUI','JZ251126@GMAIL.COM','1234567',1);
INSERT INTO DUENOS (NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,DIRECCION,BARRIO,EMAIL,TELEFONO,ID_TIPO_IDENTIFICACION) VALUES ('963258741','DANIELA','VELEZ','CR 85 # 116-26','BUENOS AIRES','VELEZ116@HOTMAIL.COM','639574',1);

SELECT * FROM DUENOS;

#TIPO_CONSULTA
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('VACUNACION','30 MINUTOS');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('ESTERILIZACION','2 HORAS');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('COMPORTAMIENTO INDESEABLE','1 HORA');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('ANTIPARASITARIOS EXTERNOS','1 HORA');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('CELO','1 HORA');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('LEISHMANIOSIS','1 HORA');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('IDENTIFICACION','1 HORA');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA,TIEMPO_DURACION) VALUES ('CONTROL','1 HORA');

SELECT * FROM TIPO_CONSULTA;


#Especies
INSERT INTO ESPECIE (DESCRIPCION) VALUES ('PERRO');
INSERT INTO ESPECIE (DESCRIPCION) VALUES ('GATO');
INSERT INTO ESPECIE (DESCRIPCION) VALUES ('PATO');
INSERT INTO ESPECIE (DESCRIPCION) VALUES ('CABALLO');
INSERT INTO ESPECIE (DESCRIPCION) VALUES ('HAMSTER');

SELECT * FROM especie;

#Raza
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AiredaleTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AkitaInu',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AlaskanMalamute',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AmericanCockerSpaniel',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AmericanPitbullTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AustralianTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BalkanHound',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Basenji',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BassetHound',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Beagle',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BeardedCollie',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Beauceron',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BichónHabanero',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BichónMaltés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bloodhound oPerrodeSanHuberto',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bobtail',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BorderTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Borzoi',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BostonTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bóxer',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BoyeroAustraliano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BoyerodeFlandes',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BracoAlemán',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BracoFrancés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BretónEspanol',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BullTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BulldogFrancés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BulldogInglés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bullmastiff',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Caniche',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Carlino',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ChartPolski',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Chihuahua',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ChinJaponés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Chowchow',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('CimarrónUruguayo',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('CockerSpanielInglés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Collie',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('CrestadoChino',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Dálmata',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('DeutschDrahthaar',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Doberman',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('DogoAlemán',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('DogoArgentino',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('DogodeBurdeos',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('FilaBrasileno',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('FoxTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('FoxhoundInglés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('GalgoEspanol',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('GoldenRetriever',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('GosDAtura',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('GrifóndeBohemia',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Hovawart',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('HuskySiberiano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('IcelandSheepdog',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('IrishWolfhound',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('JackRussellTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('KelpieAustraliano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Kuvasz',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('LabradorRetriever',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('LebrelAfgano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('LebrelEscocés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Leonberger',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('LhasaApso',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('MastíndelosPirineos',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Otterhound',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PastorAlemán',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PastorBelga',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PastorGanaderoAustraliano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PastorGarafiano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Papillón',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Pequinés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PembrokeWelshCorgi',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PerrodeAguaEspanol',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PerrodeAguaFrancés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PerrosinPeloMexicanooXoloitzcuintle',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PerrosinPelodelPerú',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PetitBassetGriffon',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Pinscher',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PodencoCanario',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PodencoIbicenco',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PointerInglés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Pomerania',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PresaCanario',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Puli',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('RatónBodegueroAndaluz',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Retrieverdepelorizado',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Rottweiler',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('SanBernardo',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Samoyedo',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Schnauzer',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ScottishTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('SetterIrlandés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('SharPei',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ShetlandSheepdog',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ShihTzu',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Spinoneitaliano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Teckel',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Terranova',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('TerrierAustraliano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('TerrierCheco',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('TerrierJaponés',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('TerrierTibetano',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('TosaInu',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Weimaraner',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('WestHighlandWhiteTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('YorkshireTerrier',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Criollo',1);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Abisinio',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AmericanCurl',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AngoraTurco',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Ashera',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AzulCubano',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('AzulRuso',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Balinés',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bengalí',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Birmano',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BobtailJaponés',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bombay',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BosquedeNoruega',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('BritishShorthair',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Burmés',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Burmilla',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Cartujo oChartreaux',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ComúnEuropeo',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('CornishRex',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('DevonRex',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Exótico',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Himalayo ',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Korat',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('MaineCoon',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Manx',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('MauEgipcio',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Munchkin',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Nebelung',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Oriental',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Persa',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PersaChinchilla',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PersaTabby',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Peterbald',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Ragamuffin',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Ragdoll',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Rex',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ScottishFold',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('SelkirkRex',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Siamés',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Siberiano',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Snowshoe',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Somalí',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Sphynx',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('VanTurco',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Criollo',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Carey',2);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('doméstico',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('azulón',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('gargantillo',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Cercetacolorada',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('mandarín',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('real',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('criollo',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('malvasíaaustraliano',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('deTorrente',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Sirirícariblanco',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('arlequín​',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('pecoso',3);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Appaloosa',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PintooAmericanPaint',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('CuartodeMilla',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Árabe',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PuraSangreInglés',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Shire',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Bretón',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Belgadetiro',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Frisón',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Percherón',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Tinker, Gipsy,o IrishCob',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Akhal-Teke',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Peruanodepaso',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('Criollocolombiano',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('PuraRazaEspanol o Andaluz',4);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('sirio',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('ruso',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('chino',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('panda',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('angora',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('deCampbell',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('roborovski',5);
INSERT INTO RAZA (DESCRIPCION,ID_ESPECIE) VALUES('albinodeojosrojos',5);

SELECT * FROM raza;

#Mascotas
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('SAMY','5 KG',STR_TO_DATE('17-06-2018','%d-%m-%Y'),'HEMBRA',153);
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('LUCY','4 KG',STR_TO_DATE('18-07-2017','%d-%m-%Y'),'HEMBRA',152);
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('JIRAFA','7 KG',STR_TO_DATE('12-01-2018','%d-%m-%Y'),'HEMBRA',153);
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('ZEUS','15 KG',STR_TO_DATE('20-12-2015','%d-%m-%Y'),'MACHO',5);
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('PERSEO','12 KG',STR_TO_DATE('31-05-2020','%d-%m-%Y'),'MACHO',42);
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('KILYAN','6 KG',STR_TO_DATE('22-10-2022','%d-%m-%Y'),'MACHO',37);
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) VALUES ('KEYLA','7 KG',STR_TO_DATE('25-03-2021','%d-%m-%Y'),'HEMBRA',37);

SELECT * FROM mascotas;

#DueNos-Mascotas

INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (1,1);
INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (6,2);
INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (4,3);
INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (3,4);
INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (7,1);
INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (5,5);
INSERT INTO DUENOS_MASCOTAS (ID_MASCOTAS,ID_DUENOS) VALUES (2,6);

SELECT * FROM DUENOS_MASCOTAS;

#Tratamiento
INSERT INTO TRATAMIENTO (DESCRIPCION,DURACION,PRECIO) VALUES ('CHEQUEO','1 HORA','120000');
INSERT INTO TRATAMIENTO (DESCRIPCION,DURACION,PRECIO) VALUES ('VACUNACION','30 MINUTOS','50000');
INSERT INTO TRATAMIENTO (DESCRIPCION,DURACION,PRECIO) VALUES ('DESPARACITACION','30 MINUTOS','65200');

SELECT * FROM tratamiento;


#Codigo de diagnostico
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('A00-B99','Ciertas enfermedades infecciosas y parasitarias');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('C00-D48','Neoplasias');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('E00-E90','Enfermedades endocrinas, nutricionales y metabólicas');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('F00-F99','Trastornos mentales y del comportamiento');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('G00-G99','Enfermedades del sistema nervioso');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('H00-H59','Enfermedades del ojo y sus anexos');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('H60-H95','Enfermedades del oído y de la apófisis mastoides');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('I00-I99','Enfermedades del aparato circulatorio');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('J00-J99','Enfermedades del aparato respiratorio');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('K00-K93','Enfermedades del aparato digestivo');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('L00-L99','Enfermedades de la piel y el tejido subcutáneo');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('M00-M99','Enfermedades del sistema osteomuscular y del tejido conectivo');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('N00-N99','Enfermedades del aparato genitourinario');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('O00-O99','Embarazo, parto y puerperio');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('P00-P96','Ciertas afecciones originadas en el periodo perinatal');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('Q00-Q99','Malformaciones congénitas, deformidades y anomalías cromosómicas');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('R00-R99','Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('S00-T98','Traumatismos, envenenamientos y algunas otras consecuencias de causa externa');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('V01-Y98','Causas externas de morbilidad y de mortalidad');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('Z00-Z99','Factores que influyen en el estado de salud y contacto con los servicios de salud');
INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('U00-U99','Códigos para situaciones especiales');

SELECT * FROM cod_diagnostico;

#Citas
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('23-08-2021','%d-%m-%Y'),'12:18:38','13:15:16','ENVIAR MEDICACIÓN',8,1,1,19,10);
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('12-12-2023','%d-%m-%Y'),'08:08:36','09:38:04','ENVIAR EXAMENES',4,2,3,7,4);
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('27-01-2022','%d-%m-%Y'),'12:23:15','15:10:43','TODO ESTA BIEN',3,3,2,20,4);
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('01-07-2022','%d-%m-%Y'),'10:32:31','11:18:57','ENVIAR TRATAMIENTO',1,4,3,21,2);
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('17-11-2021','%d-%m-%Y'),'13:16:12','14:43:37','TODO ESTA BIEN',3,5,2,9,21);
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('08-04-2023','%d-%m-%Y'),'11:19:18','12:13:36','ENVIAR MEDICACIÓN',5,6,3,13,4);
INSERT INTO citas (FECHA,HORA_INICIO,HORA_FIN,OBSERVACIONES,ID_TIPO_CONSULTA,ID_MASCOTAS,ID_TRATAMIENTO,ID_COD_DIAGNOSTICO_PRINCIPAL,ID_COD_DIAGNOSTICO_SECUNDARIO) VALUES (STR_TO_DATE('15-11-2021','%d-%m-%Y'),'10:49:52','11:21:14','ENVIAR TRATAMIENTO',3,7,1,17,13);

SELECT * FROM citas;

#Facturacion

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('133509','0:56','126017','PAGO','',STR_TO_DATE('23-08-2021','%d-%m-%Y'),1);

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('79139','1:29','118005','PENDIENTE','FALTA DEBITAR',STR_TO_DATE('12-12-2023','%d-%m-%Y'),2);

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('102299','2:47','285527','PAGO','',STR_TO_DATE('27-01-2022','%d-%m-%Y'),3);

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('39091','0:46','30252','PENDIENTE','FALTA DEBITAR',STR_TO_DATE('01-07-2022','%d-%m-%Y'),4);

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('92018','1:27','134065','PENDIENTE','FALTA DEBITAR',STR_TO_DATE('17-11-2021','%d-%m-%Y'),5);

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('29132','0:54','26364','PAGO','',STR_TO_DATE('08-04-2023','%d-%m-%Y'),6);

INSERT INTO FACTURACION (VALOR_HORA,DURACION,VALOR_TOTAL,ESTADO_FACTURA,OBSERVACIONES,FECHA_FACTURACION,ID_CITAS)
VALUES ('60456','0:31','31605','PAGO','',STR_TO_DATE('15-11-2021','%d-%m-%Y'),7);

SELECT * FROM facturacion;


INSERT INTO TRATAMIENTO (DESCRIPCION,DURACION,PRECIO) VALUES ('PENDIENTE POR REVISIÓN','0 HORA','0')

INSERT INTO COD_DIAGNOSTICO (CODIGO,DESCRIPCION) VALUES ('0','PENDIENTE POR CITA')