DELIMITER //
CREATE PROCEDURE `SP_CITAS_AGENDADAS_COMPLETO` (
)
COMMENT 'Procedimiento almacenado para la consulta de todas las citas.'
BEGIN
SELECT M.NOMBRE AS 'mascota', E.DESCRIPCION AS 'especie', CD.CODIGO AS 'codigoPrincipal', CD2.CODIGO AS 'codigoSecundario', 
LEFT(C.FECHA,10) AS 'fecha', C.HORA_INICIO AS horaInicio, C.HORA_FIN AS horaFin, TC.NOMBRE_CONSULTA AS 'tipoConsulta', T.DESCRIPCION AS 'tratamiento', C.OBSERVACIONES AS observaciones
FROM mascotas M
INNER JOIN raza R ON R.ID_RAZA = M.ID_RAZA
INNER JOIN especie E ON E.ID_ESPECIE = R.ID_ESPECIE
INNER JOIN citas	C ON C.ID_MASCOTAS = M.ID_MASCOTAS
INNER JOIN cod_diagnostico CD ON CD.ID_COD_DIAGNOSTICO = C.ID_COD_DIAGNOSTICO_PRINCIPAL
INNER JOIN cod_diagnostico CD2 ON CD2.ID_COD_DIAGNOSTICO = C.ID_COD_DIAGNOSTICO_SECUNDARIO
INNER JOIN tipo_consulta TC ON TC.ID_TIPO_CONSULTA = C.ID_TIPO_CONSULTA
INNER JOIN tratamiento T ON T.ID_TRATAMIENTO = C.ID_TRATAMIENTO;
END//
DELIMITER ;


CALL SP_CITAS_AGENDADAS_COMPLETO();

##################TABLA CLIENTES#######################


DELIMITER //
CREATE PROCEDURE `SP_AGREGAR_DUENOS` (
IN `ID_TIPO_IDENTIFICACION` INT,
IN `NUMERO_IDENTIFICACION` VARCHAR(100),
IN `NOMBRES` VARCHAR(100),
IN `APELLIDOS` VARCHAR(100),
IN `BARRIO` VARCHAR(100),
IN `DIRECCION` VARCHAR(200),
IN `EMAIL` VARCHAR(150),
IN `TELEFONO` VARCHAR(100)
)
COMMENT 'Procedimiento almacenado para agregar dueños.'
BEGIN
INSERT INTO DUENOS(ID_TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,BARRIO,DIRECCION,EMAIL,TELEFONO) 
VALUES (ID_TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION,NOMBRES,APELLIDOS,BARRIO,DIRECCION,EMAIL,TELEFONO);
END//
DELIMITER ;


CALL SP_AGREGAR_DUENOS(1,'3333333333','thomaspruebaDOS','lozanopruebaDOS','conquistadores#54','la60pa','lozssssanito@prueba.com','3333330');



DELIMITER //
CREATE PROCEDURE `SP_AGREGAR_MASCOTAS` (
IN `NOMBRE` VARCHAR(100),
IN `PESO` VARCHAR(100),
IN `FECHA_NACIMIENTO` DATE,
IN `SEXO` VARCHAR(50),
IN `ID_RAZA` INT
)
COMMENT 'Procedimiento almacenado para agregar mascotas.'
BEGIN
INSERT INTO MASCOTAS (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA ) 
VALUES (NOMBRE,PESO,FECHA_NACIMIENTO,SEXO,ID_RAZA);
END//
DELIMITER ;


CALL SP_AGREGAR_MASCOTAS('PruebaMascota','5 KG','2018-01-01','MACHO',2);
