USE test;

CREATE TABLE TIPO_IDENTIFICACION(
ID_TIPO_IDENTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
CODIGO VARCHAR(10),
DESCRIPCION VARCHAR(100)
);

CREATE TABLE DUENOS(
ID_DUENOS INT AUTO_INCREMENT PRIMARY KEY,
NUMERO_IDENTIFICACION VARCHAR(100),
NOMBRES VARCHAR(100),
APELLIDOS VARCHAR(100),
DIRECCION VARCHAR(200),
BARRIO VARCHAR(100),
EMAIL VARCHAR(150),
TELEFONO VARCHAR(100),
ID_TIPO_IDENTIFICACION INT,
FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION)
);

CREATE TABLE TIPO_CONSULTA(
ID_TIPO_CONSULTA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_CONSULTA VARCHAR(100),
TIEMPO_DURACION VARCHAR(30)
);

CREATE TABLE ESPECIE(
ID_ESPECIE INT AUTO_INCREMENT PRIMARY KEY,
DESCRIPCION VARCHAR(100)
);

CREATE TABLE RAZA(
ID_RAZA INT AUTO_INCREMENT PRIMARY KEY,
DESCRIPCION VARCHAR(100),
ID_ESPECIE INT,
FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE)
);

CREATE TABLE MASCOTAS(
ID_MASCOTAS INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
PESO VARCHAR(100),
FECHA_NACIMIENTO DATE,
SEXO VARCHAR(50),
ID_RAZA INT,
FOREIGN KEY (ID_RAZA) REFERENCES RAZA(ID_RAZA)
);

CREATE TABLE DUENOS_MASCOTAS(
ID_MASCOTAS INT,
ID_DUENOS INT,
FOREIGN KEY (ID_MASCOTAS) REFERENCES MASCOTAS(ID_MASCOTAS),
FOREIGN KEY (ID_DUENOS) REFERENCES DUENOS(ID_DUENOS)
);

CREATE TABLE TRATAMIENTO(
ID_TRATAMIENTO INT AUTO_INCREMENT PRIMARY KEY,
DESCRIPCION VARCHAR(100),
DURACION VARCHAR(30),
PRECIO INT
);

CREATE TABLE COD_DIAGNOSTICO(
ID_COD_DIAGNOSTICO INT AUTO_INCREMENT PRIMARY KEY,
CODIGO VARCHAR(10),
DESCRIPCION VARCHAR(100)
);

CREATE TABLE CITAS(
ID_CITAS INT AUTO_INCREMENT PRIMARY KEY,
FECHA DATE,
HORA_INICIO TIME,
HORA_FIN TIME,
OBSERVACIONES VARCHAR(500),
ID_TIPO_CONSULTA INT,
ID_MASCOTAS INT,
ID_TRATAMIENTO INT,
ID_COD_DIAGNOSTICO_PRINCIPAL INT,
ID_COD_DIAGNOSTICO_SECUNDARIO INT,
FOREIGN KEY (ID_TIPO_CONSULTA) REFERENCES TIPO_CONSULTA(ID_TIPO_CONSULTA),
FOREIGN KEY (ID_MASCOTAS) REFERENCES MASCOTAS(ID_MASCOTAS),
FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTO(ID_TRATAMIENTO),
FOREIGN KEY (ID_COD_DIAGNOSTICO_PRINCIPAL) REFERENCES COD_DIAGNOSTICO(ID_COD_DIAGNOSTICO),
FOREIGN KEY (ID_COD_DIAGNOSTICO_SECUNDARIO) REFERENCES COD_DIAGNOSTICO(ID_COD_DIAGNOSTICO)
);


CREATE TABLE FACTURACION(
ID_FACTURACION INT AUTO_INCREMENT PRIMARY KEY,
VALOR_HORA INT,
DURACION VARCHAR(30),
VALOR_TOTAL INT,
ESTADO_FACTURA VARCHAR(50),
OBSERVACIONES VARCHAR(500),
FECHA_FACTURACION DATE,
ID_CITAS INT,
FOREIGN KEY (ID_CITAS) REFERENCES CITAS(ID_CITAS)
);




